import "./globals.css";
import { NavBar } from "./componet/navBar";
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`antialiased pb-12`}>
        {children}
        <NavBar />
      </body>
    </html>
  );
}
