import "../globals.css";
export const metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <div className={`bg-gray-950 `}>{children}</div>;
}
